
[default]
SCHOLAR_ENV = "default"
SCHOLAR_ISSUEDB_PATH = "data/issue_db.sqlite"
I18N_LANG_DEFAULT = "en"
ELASTICSEARCH_QUERY_BASE = "http://localhost:9200"
ELASTICSEARCH_QUERY_FULLTEXT_INDEX = "scholar_fulltext"
ELASTICSEARCH_WRITE_BASE = "http://localhost:9200"
ELASTICSEARCH_WRITE_FULLTEXT_INDEX = "scholar_fulltext_v01"
ELASTICSEARCH_PUBLIC_URL = "http://localhost:9292"
THUMBNAIL_URL_PREFIX = "https://blobs.fatcat.wiki/thumbnail/pdf/"
SANDCRAWLER_DB_API = "http://wbgrp-svc506.us.archive.org:3030"
SANDCRAWLER_S3_API = "wbgrp-svc169.us.archive.org:8333"
GROBID_HOST = "https://grobid.qa.fatcat.wiki"
KAFKA_BROKERS = []
FATCAT_API_HOST = "https://api.fatcat.wiki/v0"
ELASTICSEARCH_FATCAT_BASE = "https://search.fatcat.wiki"
ELASTICSEARCH_FATCAT_RELEASE_INDEX = "fatcat_release"
INDEX_WORKER_BATCH_SIZE = 50
SENTRY_DSN = ""
ENABLE_GOATCOUNTER = false
GOATCOUNTER_ENDPOINT = "https://goatcounter.scholar.fatcat.wiki/count"
GOATCOUNTER_SCRIPT_URL = "https://goatcounter.scholar.fatcat.wiki/count.js"
ENABLE_PROMETHEUS = false
ENABLE_CITATION_QUERY = true
EXCLUDE_WEB_CONTAINER_IDENTS = []
EXCLUDE_WEB_PUBLISHERS = []

[test]
SCHOLAR_ENV = "test"
FATCAT_API_HOST = "http://disabled-during-tests-bogus.xyz:3333"
ELASTICSEARCH_FATCAT_BASE = "http://disabled-during-tests-bogus.xyz:3333"
ELASTICSEARCH_QUERY_BASE = "http://disabled-during-tests-bogus.xyz:3333"
ELASTICSEARCH_WRITE_BASE = "http://disabled-during-tests-bogus.xyz:3333"
ELASTICSEARCH_WRITE_FULLTEXT_INDEX = "dummy_index"
ELASTICSEARCH_PUBLIC_URL = "http://disabled-during-tests-bogus.xyz:3333"
SANDCRAWLER_DB_API = "http://disabled-during-tests-bogus.xyz:3333"
SANDCRAWLER_S3_API = "disabled-during-tests-bogus.xyz:8333"
GROBID_HOST = "http://disabled-during-tests-bogus.xyz:3333"
SCHOLAR_ISSUEDB_PATH = ":memory:"

[development]
SCHOLAR_ENV = "dev"
ELASTICSEARCH_QUERY_BASE = "http://localhost:9200"
ELASTICSEARCH_QUERY_FULLTEXT_INDEX = "dev_scholar_fulltext"
ELASTICSEARCH_WRITE_BASE = "http://localhost:9200"
ELASTICSEARCH_WRITE_FULLTEXT_INDEX = "dev_scholar_fulltext"
ELASTICSEARCH_PUBLIC_URL = "http://localhost:9200"
KAFKA_BROKERS = ["localhost"]

[development-qa]
SCHOLAR_ENV = "dev"
ELASTICSEARCH_QUERY_BASE = "http://scholar-svc500.fatcat.wiki:9292"
ELASTICSEARCH_PUBLIC_URL = "http://scholar-svc500.fatcat.wiki:9292"

[qa]
SCHOLAR_ENV = "qa"
ELASTICSEARCH_QUERY_BASE = "http://scholar-svc500.fatcat.wiki:9292"
ELASTICSEARCH_WRITE_BASE = "http://localhost:9200"
ELASTICSEARCH_PUBLIC_URL = "http://scholar-svc500.fatcat.wiki:9292"
KAFKA_BROKERS = ["wbgrp-svc263.us.archive.org"]

[prod]
SCHOLAR_ENV = "prod"
ONION_DOMAIN = "scholar.archivev3qli37bju4rlh27glh24lljyezwxf4pokmrdbpefjlcrp5id.onion"
ELASTICSEARCH_QUERY_BASE = "http://localhost:9292"
ELASTICSEARCH_QUERY_FULLTEXT_INDEX = "scholar_fulltext"
ELASTICSEARCH_WRITE_BASE = "http://localhost:9200"
ELASTICSEARCH_WRITE_FULLTEXT_INDEX = "scholar_fulltext_v01_20210128"
ELASTICSEARCH_PUBLIC_URL = "http://scholar-svc500.fatcat.wiki:9292"
KAFKA_BROKERS = ["wbgrp-svc263.us.archive.org"]
ENABLE_GOATCOUNTER = true
GOATCOUNTER_ENDPOINT = "/goatcounter/count"
GOATCOUNTER_SCRIPT_URL = "/goatcounter/count.js"
